---
version: 2.1

orbs:
  orb-tools: twdps/orb-tools@dev:latest

dev-release-filter: &dev-release-filter
  branches:
    only: /master/
  tags:
    ignore: /.*/

patch-tag-publish-filter: &patch-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^patch.*/

minor-tag-publish-filter: &minor-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^minor.*/

major-tag-publish-filter: &major-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^major.*/


workflows:
  version: 2

  dev-release-orb-executor-tools:
    jobs:
      - orb-tools/validate:
          filters: *dev-release-filter

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: twdps/executor-tools
          filters: *dev-release-filter
          requires:
            - orb-tools/validate

      - approve-release:
          type: approval
          requires:
            - orb-tools/publish-dev
          filters: *dev-release-filter

      - orb-tools/release-tag:
          context: orb-publishing
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *dev-release-filter
          requires:
            - approve-release

  promote-orb-tools:
    jobs:
      # patch, minor, or major publishing, depending on which orb source
      # files have been modified (that logic lives in the
      # release-tag job's source)
      - orb-tools/promote-dev-to-prod:
          name: patch-release
          context: orb-publishing
          release: patch
          orb-name: twdps/executor-tools
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *patch-tag-publish-filter

      - orb-tools/promote-dev-to-prod:
          name: minor-release
          context: orb-publishing
          release: minor
          orb-name: twdps/executor-tools
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *minor-tag-publish-filter

      - orb-tools/promote-dev-to-prod:
          name: major-release
          context: orb-publishing
          release: major
          orb-name: twdps/executor-tools
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *major-tag-publish-filter
